import { defineField, defineType } from "sanity";

export const doctorSchema = defineType({
  name: "doctor",
  title: "Doctor",
  type: "document",
  groups: [
    { name: "main", title: "Main", default: true },
    { name: "homecard", title: "Home card" },
    { name: "listing", title: "Doctors listing" },
    { name: "detail", title: "Detail page" },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    // Main
    defineField({ name: "name", title: "Full name", type: "string", group: "main", validation: (r) => r.required() }),
    defineField({
      name: "slug",
      title: "URL slug",
      type: "slug",
      group: "main",
      options: { source: "name", maxLength: 96 },
      validation: (r) => r.required(),
      description: "The /doctors/<slug> URL.",
    }),
    defineField({ name: "title", title: "Title / role", type: "string", group: "main", validation: (r) => r.required() }),
    defineField({
      name: "portrait",
      title: "Portrait image",
      type: "image",
      options: { hotspot: true },
      group: "main",
      description: "Used on the home card, doctors listing and detail page.",
    }),
    defineField({
      name: "imageVariant",
      title: "Fallback gradient",
      type: "string",
      group: "main",
      options: { list: ["d1", "d2", "d3"].map((v) => ({ title: v, value: v })) },
      initialValue: "d1",
    }),
    defineField({ name: "years", title: "Years practising", type: "number", group: "main", validation: (r) => r.required() }),
    defineField({
      name: "order",
      title: "Sort order",
      type: "number",
      initialValue: 0,
      group: "main",
    }),
    // Home card
    defineField({
      name: "focusLine",
      title: "Focus line",
      type: "string",
      group: "homecard",
      description: 'Shown on the homepage card under "Focus". e.g. "Skin · Hair · Nail".',
    }),
    defineField({
      name: "homeBio",
      title: "Homepage bio",
      type: "text",
      rows: 4,
      group: "homecard",
      description: "Shown on the homepage doctor card.",
    }),
    // Listing
    defineField({
      name: "shortLine",
      title: "Listing eyebrow line",
      type: "string",
      group: "listing",
      description: 'e.g. "Cosmetic dermatology · Acne & scars · Hair restoration"',
    }),
    defineField({ name: "listBio", title: "Listing bio", type: "text", rows: 5, group: "listing" }),
    defineField({
      name: "statCreds",
      title: "Stat badges (3 expected)",
      type: "array",
      of: [{ type: "statCred" }],
      group: "listing",
      validation: (r) => r.max(3),
    }),
    defineField({
      name: "listExpertise",
      title: "Quick expertise tags",
      type: "array",
      of: [{ type: "string" }],
      group: "listing",
    }),
    // Detail
    defineField({ name: "tagline", title: "Personal quote / tagline", type: "text", rows: 3, group: "detail" }),
    defineField({ name: "detailBio", title: "Full detail bio", type: "text", rows: 6, group: "detail" }),
    defineField({
      name: "credentials",
      title: "Credentials",
      type: "array",
      of: [{ type: "credential" }],
      group: "detail",
    }),
    defineField({
      name: "timeline",
      title: "Education & experience timeline",
      type: "array",
      of: [{ type: "timelineEntry" }],
      group: "detail",
    }),
    defineField({
      name: "expertise",
      title: "Areas of expertise",
      type: "array",
      of: [{ type: "string" }],
      group: "detail",
      description: "Shown as pills on the detail page.",
    }),
    defineField({
      name: "treatments",
      title: "Treatments performed",
      type: "array",
      of: [{ type: "doctorTreatment" }],
      group: "detail",
    }),
    defineField({
      name: "quotes",
      title: "Patient quotes",
      type: "array",
      of: [{ type: "patientQuote" }],
      group: "detail",
    }),
    defineField({ name: "seo", title: "SEO", type: "seo", group: "seo" }),
  ],
  orderings: [
    { name: "order", title: "Manual order", by: [{ field: "order", direction: "asc" }] },
  ],
  preview: { select: { title: "name", subtitle: "title", media: "portrait" } },
});
